### ISSUE TITLE
Blank files getting created in our apps cache directory

### ISSUE THREAD

**Issue by sidn27** [IhorKlimov/SmartImagePicker#1]
Every time we select an image after cropping it, a file with it's name like 'cropped12345.jpg' gets created in the internal cache directory of our app. The same file is visible in the gallery. Is there any way to delete the file from cache folder or hide them.?
Or should the ImagePicker create the same file in Context.MODE_PRIVATE.?

**Comment by IhorKlimov** [comment]
FIxed in v 1.0.1 and I delete all previous cropped files, leaving only the last one
