### ISSUE TITLE
Camera Crashes On KitKat

### ISSUE THREAD

**Issue by saddahussain** [IhorKlimov/SmartImagePicker#11]
When image is captured using camera, the camera crashed. Gallery picker is working fine.

**Comment by martipello** [comment]
I'm running it on a htc one x running 4.4.2 and I have the same error except instead of a crash it just doesn't return anything, think this could be a bitmap too large exception

**Comment by gbenroscience** [comment]
Good library. Too bad it doesn't work on KitKat I have the same error as @saddahussain.

**Comment by saddahussain** [comment]
Developer has abandoned the project.
