### ISSUE TITLE
getImageFile returns null when crop is disabled

### ISSUE THREAD

**Issue by jourda-c** [IhorKlimov/SmartImagePicker#5]
I don't know if it's by design and you forgot to mention it, but when calling (Kotlin code) :

`imagePicker = ImagePicker(this, null, { uri ->
                imagePicker.getImageFile() // null
            }
        )
        imagePicker?.choosePicture(true)`

getImageFile() returns null. In fact in your code you only set imageFile when used with the crop activity.
Nowhere you mention this fact, you simply say that to get the file, we should call getImageFile()

**Comment by IhorKlimov** [comment]
Fixed in v 1.0.2
